// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"context"
	"github.com/google/wire"
	"github.com/huyrun/counting-mouse/src/handlers"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*handlers.App, func(), error) {
	appConfig, err := ProvideAppConfig()
	if err != nil {
		return nil, nil, err
	}
	engine := ProvideEngine()
	useCase := ProvideUseCase()
	app := &handlers.App{
		Config:  appConfig,
		Engine:  engine,
		Usecase: useCase,
	}
	return app, func() {
	}, nil
}

// wire.go:

var AppSet = wire.NewSet(
	ProvideAppConfig,
	ProvideUseCase,
	ProvideEngine,
)
