// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// CountAliveMouse mocks base method.
func (m *MockUseCase) CountAliveMouse(ctx context.Context, originalAmount, lifeSpan, n int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAliveMouse", ctx, originalAmount, lifeSpan, n)
	ret0, _ := ret[0].(int)
	return ret0
}

// CountAliveMouse indicates an expected call of CountAliveMouse.
func (mr *MockUseCaseMockRecorder) CountAliveMouse(ctx, originalAmount, lifeSpan, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAliveMouse", reflect.TypeOf((*MockUseCase)(nil).CountAliveMouse), ctx, originalAmount, lifeSpan, n)
}
