name: ci

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Run test
        run: make test-up

      - name: Post Run test
        run: make test-down